global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order-mgmt-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
